#!/bin/sh

set -e

if test "$1" = "purge"
then
	if test -e /usr/share/debconf/confmodule
	then
		. /usr/share/debconf/confmodule
		db_purge
	fi

	rm -r /etc/ssmtp 2>/dev/null || true
	if test "$?" = 1
	then
		echo "/etc/ssmtp not empty -- not removed"
	fi

	if test -L /usr/doc/ssmtp
	then
		rm -f /usr/doc/ssmtp 2>/dev/null || true
	fi
fi

# Program End
exit 0
